version: "3"


services: 
  app:
      build: 
        context:  ../Practice2/projectweb.two
      ports:  
        - '3000'
      networks:
        - loadbalancing


  app2:
      build: 
        context:  ../Practice2/projectweb.two
      ports:  
        - '3000'
      networks:
        - loadbalancing


  app3:
      build: 
        context:  ../Practice2/projectweb.two
      ports:  
        - '3000'
      networks:
        - loadbalancing

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
        - "80:80"
    networks:
      - loadbalancing
networks:
    loadbalancing: 


